### ISSUE TITLE
Cannot compile: undefined reference to K8JSON::generate

### ISSUE THREAD

**Issue by glixx** [gorthauer/vreen#28]
[ 50%] Building CXX object src/api/CMakeFiles/vreen.dir/attachment.cpp.o
[ 52%] Building CXX object src/api/CMakeFiles/vreen.dir/vreen_automoc.cpp.o
Linking CXX shared library libvreen.so
/tmp/ccUFlF89.ltrans5.ltrans.o: In function `Vreen::JSON::generate(QVariant const&, int)':
/home/user/rpmbuild/BUILD/vreen-git20140410/src/api/json.cpp:54: undefined reference to `K8JSON::generate(QByteArray&, QVariant const&, int)'
/tmp/ccUFlF89.ltrans5.ltrans.o: In function `Vreen::JSON::parse(QByteArray const&)':
/home/user/rpmbuild/BUILD/vreen-git20140410/src/api/json.cpp:41: undefined reference to `K8JSON::parseRecord(QVariant&, unsigned char const*, int*)'
collect2: error: ld returned 1 exit status
src/api/CMakeFiles/vreen.dir/build.make:818: recipe for target 'src/api/libvreen.so.0.9.5' failed
make[2]: *** [src/api/libvreen.so.0.9.5] Error 1
CMakeFiles/Makefile2:180: recipe for target 'src/api/CMakeFiles/vreen.dir/all' failed
make[1]: *** [src/api/CMakeFiles/vreen.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gorthauer** [comment]
Now k8json not used.
